### PR TITLE
Fixed the font pixel scaling

### LINKED ISSUE #223: Font rendering sizes are not correct
**Summary:**
I used a font that is made for pixel perfect text, at size 9. In tetra, it looks very blurry with size 9, but looks fine in size 10.
Tried the font in godot engine, where it works fine at size 9, but not 10. The font is "Vector", from [Chevy Ray](https://chevyray.itch.io/pixel-fonts)'s font pack. I am sure it is reproducible with other (free) fonts as well.

Edit: I tried with another font that should be pixel perfect at size 10, but I could't get it to work at any whole pixel size.

How it looks at size 9:
image

How it looks at size 10 (expected this at size 9):
image

### PR DESCRIPTION
**Pull request by fossegutten**
[Found answer here](https://github.com/alexheretic/ab-glyph/issues/14)

Fixes #223

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Aha, nice one, this makes much more sense! I will make sure to merge this and credit you when I put together 0.6 😄 Given there's a couple of other breaking change issues and some dependency updates that need doing, that probably won't be too far in the future.

**Comment by 17cupsofcoffee** [comment]
PC is up and running again, so finally able to try this out for myself 😄 

This has fixed a load of pixel fonts that were previously too blurry for me to use:

image

This is absolutely essential for the kind of games I want to make with Tetra, and it's been driving me crazy for literally years! Cannot thank you enough for figuring this one out ❤️

**Comment by fossegutten** [comment]
Good to hear PC is up and running again! Those fonts look pretty crisp to my eyes  😄

**Comment by 17cupsofcoffee** [comment]
I have rebased this onto the `0.6` branch and merged it :+1: It's turning into a fairly big release and I might want to do an alpha version, so wanted to make sure this was included.

Thank you for the PR 😄

**Pull request closed without merging**
