### PR TITLE
Add mouse grab

### PR DESCRIPTION
**Pull request by tatref**
Title is pretty self explanatory.

Maybe I could also add a method in the ContextBuilder?

Tell me if you're OK with this change.

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
Thank you for the PR! If I'm understanding correctly, this feature would allow the user to lock the cursor within the window? If so, that's definitely a feature I'd like to add at some point.

I'll do some research into what this feature is called/how it functions in other frameworks and see if I feel like this needs any tweaks in terms of naming or functionality, will likely use this PR as the initial implementation though.

**Comment by tatref** [comment]
Your understanding is correct!
To be honest, I don't know anything about SDL, it was just a quick hack.

I tested on Windows, and it works fine.

**Comment by 17cupsofcoffee** [comment]
FYI, I've not forgotten about this PR 🙂 Just been a bit busy with other features recently.

I've run the code locally and it seems okay - might make some naming tweaks/add to the `ContextBuilder`, but this feature will definitely be in the next version of Tetra in some shape or form.

**Comment by 17cupsofcoffee** [comment]
Doh, this was closed automatically due to the [master branch being renamed](https://twitter.com/17cupsofcoffee/status/1272155471688990722) - I will cherry pick the change manually later today.

**Comment by 17cupsofcoffee** [comment]
Done in 0a5637a, thank you for your patience!

**Pull request closed without merging**
