### PR TITLE
add support for stencils

### PR DESCRIPTION
**Pull request by tesselode**
Acknowledgements:
- @PsichiX for helping me get stencils working
- @LPGhatguy for suggesting a `StencilState` struct
- @lunabunn for design feedback

### CODE REVIEW

**Review by 17cupsofcoffee — APPROVED** [review]
Really happy with this API! Seems to give all the low level control people would need without being super verbose (think the `StencilState` methods help a lot with that).

More importantly, I can kinda understand what the stencil example is doing, despite not being very knowledgable about OpenGL stencils, which is a good sign, I think.

As discussed yesterday, my only real concern is the change to `Canvas::new` (due to it being a breaking change, and the fact that it adds extra typing/imports even when you're not using this feature). For now, I'll probably tweak the changes to be non-breaking, and then revisit that when I come to do 0.7.

**Comment by 17cupsofcoffee** [comment]
Thank you again for the PR! 🚀

**Comment by tesselode** [comment]
of course!

**Comment by 17cupsofcoffee** [comment]
FYI - I just pushed a commit changing `CanvasSettings` into a builder, as otherwise it wouldn't be possible to add extra settings (e.g. depth buffers, texture formats, mipmaps) without each one being a breaking change. Should still be basically the same amount of typing (minus one import, which is kinda nice), but a bit more future proof.

**Pull request merged**
