### PR TITLE
make text scaling respect the default filter mode setting

### PR DESCRIPTION
**Pull request by tesselode**

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
This looks mostly right, but I don't think there's any need to clear the cache/invalidate geometry when the filter mode changes. You should just be able to change the filter mode on the existing packed texture, unless I'm missing something?

**Comment by tesselode** [comment]
you're right!

**Review by 17cupsofcoffee — APPROVED** [review]
🚀 Looks good, will merge as soon as CI is done running.

**Comment by 17cupsofcoffee** [comment]
Thank you!

**Pull request merged**
