### PR TITLE
ECS example with Legion

### PR DESCRIPTION
**Pull request by rghartmann**
Things to note:

In order for this to compile and work, you'll need to add Legion to `Cargo.toml`:

```toml
legion = { version = "0.4.0", optional = true }
```

I am new to Rust and thus not very familiar with Cargo yet, so I'm not sure how it handles dependencies for `examples`. It'd be nicer if the dependency could only be added to the scope of this example, instead of being available to anyone using the library; Even as I made it optional, it could imply a broader support of Tetra for Legion, which is obviously not the intention here.

I based myself off `bunnymark.rs`, making small changes along the way. I never intended it to be a full conversion of that example to use ECS/Legion. However, if you feel that it's confusing as it is, I can always make it match, or contribute a different ECS example altogether. I'm happy either way!

### CODE REVIEW

**Comment by 17cupsofcoffee** [comment]
🎉 🎉 🎉 

This looks good at first glance, and the way you've structured the code is in line with how people have used ECS with Tetra in the past (i.e. systems for `update`, simple queries for `draw`). Will give it a proper try locally after work!

With regards to the dependency, you can exclude Legion from the main build by putting it in the `[dev-dependencies]` section of `Cargo.toml` - that way it will only get compiled for examples/tests. I think there are ways you could make it specifically only get compiled for this single example, but it's probably not worth the trouble unless Legion *really* slows the builds down. Will check the timings once I get the build working 😄

**Comment by 17cupsofcoffee** [comment]
I made a few code style tweaks and tried to bring the behaviour more in line with the existing Bunnymark example 🙂 Debating maybe moving the spawning into a system too, to give an example of how to handle input, but might save that for a later change.

**Comment by rghartmann** [comment]
Looks great! And agreed, I can follow up with another PR to have the input/spawning handled by a system.

**Comment by 17cupsofcoffee** [comment]
Let's start with this then 🚀

**Comment by 17cupsofcoffee** [comment]
Thank you for the PR 😄

**Pull request merged**
