### PR TITLE
Added a helper function to the camera to calculate the visible rectangle

### PR DESCRIPTION
**Pull request by VictorKoenders**
Small helper method that I use in my own code, and I figured other people would have a use for. Returns the visible viewport rectangle in the world based on the position and scale.

This does not take into account rotation. I need to figure out the math for that. If anyone knows how to do this off the top of their heads then they can add it to this PR.

### CODE REVIEW

**Comment by VictorKoenders** [comment]
Added code to calculate the minimum rectangle containing the rotated camera view. I'd appreciate if someone that is actually good at math could double-check this. It's very possible that my logic is flawed or that there is a better way to do this.

**Comment by 17cupsofcoffee** [comment]
This is definitely something I'd like to add - need to have a think about the behaviour around rotation/compare with how this stuff works in other frameworks, but I don't think this is far off what we'd want.

> I'd appreciate if someone that is actually good at math could double-check this.

I am not that someone 😆

**Comment by 17cupsofcoffee** [comment]
FYI, I've not forgotten about this! I just need a bit of time to play around with it, compare with other frameworks' implementations and see if there's a simpler approach to the maths. Will definitely merge this in some shape or form before 0.4.2.

**Comment by 17cupsofcoffee** [comment]
I think I'm going to merge this as is - might tweak it a little bit before releasing 0.4.2 but the behaviour seems pretty much like what I'd expect.

The only bit that gave me pause was that this method calculates the `Rectangle` itself, while `project` and `unproject` use the matrix (which has to be `update`d), but it'd probably be a lot slower to use the matrix here. If anything I'd want to make those methods match this one, rather than vice-versa.

**Comment by 17cupsofcoffee** [comment]
Added to the changelog, thank you again for the PR!

**Pull request merged**
